import 'package:car_rental_for_customer/models/notification.dart';

final notificationMock = [
  Notification(
    id: '1',
    body: 'body1',
    title: 'title1',
    type: 'type1',
    createdAt: DateTime.now(),
    isRead: false,
  ),
  Notification(
    id: '2',
    body: 'body2',
    title: 'title2',
    type: 'type2',
    createdAt: DateTime.now(),
    isRead: false,
  ),
  Notification(
    id: '3',
    body: 'body3',
    title: 'title3',
    type: 'type3',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '4',
    body: 'body4',
    title: 'title4',
    type: 'type4',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '5',
    body: 'body5',
    title: 'title5',
    type: 'type5',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '6',
    body: 'body6',
    title: 'title6',
    type: 'type6',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '7',
    body: 'body7',
    title: 'title7',
    type: 'type7',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '8',
    body: 'body8',
    title: 'title8',
    type: 'type8',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '9',
    body: 'body9',
    title: 'title9',
    type: 'type9',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '10',
    body: 'body10',
    title: 'title10',
    type: 'type10',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '11',
    body: 'body11',
    title: 'title11',
    type: 'type11',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '12',
    body: 'body12',
    title: 'title12',
    type: 'type12',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '13',
    body: 'body13',
    title: 'title13',
    type: 'type13',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '14',
    body: 'body14',
    title: 'title14',
    type: 'type14',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '15',
    body: 'body15',
    title: 'title15',
    type: 'type15',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '16',
    body: 'body16',
    title: 'title16',
    type: 'type16',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '17',
    body: 'body17',
    title: 'title17',
    type: 'type17',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '18',
    body: 'body18',
    title: 'title18',
    type: 'type18',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '19',
    body: 'body19',
    title: 'title19',
    type: 'type19',
    createdAt: DateTime.now(),
    isRead: true,
  ),
  Notification(
    id: '20',
    body: 'body20',
    title: 'title20',
    type: 'type20',
    createdAt: DateTime.now(),
    isRead: true,
  ),
];
